---
deployment:
  tasks:
    - export DEPLOYPATH=/home/username/public_html
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -r public/* $DEPLOYPATH/
  app:
    current_build_command:
      - npm install
      - npm run build
      - cp -a src/views/. public/
    environment:
      nodejs_version: lts
  cache:
    directories:
      - node_modules